### ISSUE TITLE
Allow model customization

### ISSUE THREAD

**Issue by maxxer** [bupy7/yii2-pages#1]
It would be great if it could be possible to customize the model. For example, I'd like to add a _language_ field to the page, in order to be able to show different content for different languages.

**Comment by bupy7** [comment]
You can override controller via `$controllerMap` in module and change the class model to your controller.

**Comment by bupy7** [comment]
More info: http://www.yiiframework.com/doc-2.0/yii-base-module.html#$controllerMap-detail

**Comment by maxxer** [comment]
oh great, thanks. maybe worth mentioning in the docs ;)

**Comment by bupy7** [comment]
@maxxer i think what yes )
