### ISSUE TITLE
Impervi

### ISSUE THREAD

**Issue by kaptnkage** [bupy7/yii2-pages#12]
followed all settings in config, yet Impervi outputs "true" in Add File/Picture upload box
![screen shot 2018-05-20 at 12 46 42 am](https://user-images.githubusercontent.com/8315760/40275770-4a7dffee-5bc7-11e8-8b8e-e9770db2dd1d.png)

**Comment by bupy7** [comment]
Hi! Could you please give me a config, controller and view? And text me version of extension.

**Comment by kaptnkage** [comment]
// aliases
Yii::setAlias('System',      	'/server/system');
Yii::setAlias('Library',      	'/server/library');
Yii::setAlias('Sites',      	'/server/sites');
Yii::setAlias('Users',    		'/server/users');
Yii::setAlias('BTY',      		'/server/BTY');
Yii::setAlias('app',      	    '/server/system');
Yii::setAlias('res',      		'@Library');
Yii::setAlias('common',   		'/server/system/common');
Yii::setAlias('frontend', 		'/server/system/frontend');
Yii::setAlias('backend',  		'/server/system/backend');
Yii::setAlias('api',      		'/server/system/api');

// config
'modules' => [
     'pages' => ['class' => 'bupy7\pages\Module',
            'tableName' => '{{%public_pages}}',
            'pathToImages' => '@Sites/frontend/uploads/images',
            'urlToImages' => '@webroot/uploads/images',
            'pathToFiles' => '@Sites/frontend/uploads/files',
            'urlToFiles' => '@webroot/uploads/files',
            'uploadImage' => true,
            'uploadFile' => true,
            'addImage' => true,
            'addFile' => true,
            'controllerMap' => [
                'manager' => [
                    'class' => 'bupy7\pages\controllers\ManagerController',
                    'as access' => [
                        'class' => AccessControl::className(),
                        'rules' => [
                            [
                                'allow' => true,
                                'roles' => ['editor'],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
Nothing changed in your controller or view
// extension 

"bupy7/yii2-pages": "*"

All other functions operate perfectly

Thank you for your prompt response

**Comment by bupy7** [comment]
`"bupy7/yii2-pages": "*"` - it's not a version. What version?

**Comment by kaptnkage** [comment]
I'll try updating with composer

**Comment by bupy7** [comment]
@kaptnkage Just give me output: `composer info bupy7/yii2-pages`.

**Comment by kaptnkage** [comment]
Updated
versions : * 1.3.1
it updated Impervi
all fixed now
Thanks
(sorry)
