### ISSUE TITLE
Do not display the page title

### ISSUE THREAD

**Issue by i-panov** [bupy7/yii2-pages#14]
Please add the setting in the config or in the model so that you can not display the page title. I'm using my layout and there I already have the page title. Because of this, duplication is obtained.

**Comment by bupy7** [comment]
@i-panov In the model is the best way to do it. Can you add it yourself and send me pull-request?

**Comment by bupy7** [comment]
https://github.com/bupy7/yii2-pages/issues/6#issuecomment-207322165

**Comment by i-panov** [comment]
@bupy7 ok! I did it. When can I expect a merge?

**Comment by bupy7** [comment]
As soon as possible. I need to check it and add some tests.

**Comment by i-panov** [comment]
I was hoping for a quick fix for my project. Next time I will not make you pull-request...

**Comment by bupy7** [comment]
You made not good pull-request. I made review but you ignored it. There was following: 

1: You used [short open tag](http://php.net/manual/en/language.basic-syntax.phptags.php):
> short open tag <? (which is discouraged since it is only available if enabled using the short_open_tag php.ini configuration file directive, or if PHP was configured with the --enable-short-tags option).
Must use only `<?php` open tag.

2: Configuration HTML-template is redundant, because you can [override your view](https://github.com/bupy7/yii2-pages/issues/6#issuecomment-207322165).

3: Missed the tests. 

4: The migration without backwards-compatibility.

5: There isn't translations for other language except Russian and English.

**Comment by bupy7** [comment]
https://github.com/bupy7/yii2-pages/pull/17

**Comment by i-panov** [comment]
> I made review but you ignored it.

As far as I can see, you just made a review. How could I ignore what I did not see?

> 1: You used short open tag:

I always use a short open tag. I did not think that this could be a problem. But if you do not like it, you can do it in full.

> 2: Configuration HTML-template is redundant, because you can override your view.

Here you are wrong. Do not want to overload the view just because of changing one tag in the header. It is a pity that you did not approve of this. So it would be much more convenient.

> 3: Missed the tests.

You kind of said that you write them yourself? I do not know the specifics of your code and tests. And in general, I do not know how to write them, honestly.

> 4: The migration without backwards-compatibility.

ok

> 5: There isn't translations for other language except Russian and English.

I do not know other languages.

**Comment by bupy7** [comment]
> As far as I can see, you just made a review. How could I ignore what I did not see?

No, don't. Check, please, your pull-request.

> I always use a short open tag. I did not think that this could be a problem. But if you do not like it, you can do it in full.

Short-tags will deprecated in the future.

> Here you are wrong. Do not want to overload the view just because of changing one tag in the header. It is a pity that you did not approve of this. So it would be much more convenient.

May be.

> You kind of said that you write them yourself? I do not know the specifics of your code and tests. And in general, I do not know how to write them, honestly.

Without tests I cannot be confident that your new functional work correctly.

**Comment by bupy7** [comment]
Released [v1.4.0](https://github.com/bupy7/yii2-pages/releases/tag/v1.4.0)
