### ISSUE TITLE
Url in custom layout

### ISSUE THREAD

**Issue by i-panov** [bupy7/yii2-pages#16]
I'm using my layout. It has a reference to `Url::to(['profile/index'])` which should look like this: `/profile/index`, but instead it looks like this: `/pages/profile/index` when I use pages manager (on the remaining pages the links are correct). Why is this happening?

**Comment by bupy7** [comment]
@i-panov Because of relative path. You should use absolute like `/profile/index` insted of `profile/index`.

**Comment by i-panov** [comment]
Hmm... It's strange, but it kind of helped. I did not understand what kind of relative path you were talking about - it's a route, they always record exactly as I know. I did not even know that you can start a router with a slash. Simply on all other my pages the links work correctly and without a slash at the beginning of the route.

**Comment by bupy7** [comment]
Just do `Url::to(['/profile/index'])` https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing#creating-urls
