### ISSUE TITLE
Migration default value wrong for PostgresSQL

### ISSUE THREAD

**Issue by umbalaconmeogia** [bupy7/yii2-pages#19]
The code below in `m150429_155009_create_page_table.php` will cause error when run with PostgreSQL
`'published' => Schema::TYPE_BOOLEAN . ' DEFAULT 1',`
The bug fix as below will work for MySQL, PostgreSQL, SQLite (I've tested).
`'published' => Schema::TYPE_BOOLEAN . ' DEFAULT TRUE',`
https://github.com/bupy7/yii2-pages/blob/05d2efc8b015e2019719b89255b4a1378cfdb26a/src/migrations/m150429_155009_create_page_table.php#L38

The same issue in `m180927_200917_add_display_title.php`
Current code
`$this->addColumn($this->_tableName, 'display_title', Schema::TYPE_BOOLEAN . ' DEFAULT 1');`
should be changed to
`$this->addColumn($this->_tableName, 'display_title', Schema::TYPE_BOOLEAN . ' DEFAULT TRUE');`
https://github.com/bupy7/yii2-pages/blob/05d2efc8b015e2019719b89255b4a1378cfdb26a/src/migrations/m180927_200917_add_display_title.php#L25

**Comment by bupy7** [comment]
Please, checkout master branch.

**Comment by umbalaconmeogia** [comment]
It works. Thank you.
Can you publish it to Packagist?

**Comment by bupy7** [comment]
Of course.

**Comment by bupy7** [comment]
Fixed at 1.4.1.
