### ISSUE TITLE
Migrate failed 

### ISSUE THREAD

**Issue by stronglab** [bupy7/yii2-pages#2]
error migrate: need insert initialization module in console config, or else Yii::$app->getModule('pages') return NULL and tableName is not found.

**Comment by bupy7** [comment]
Configuration of a module must be contain at the main config file.

**Comment by stronglab** [comment]
> Configuration of a module must be contain at the main config 

I know, but migration is console command. Because module not init in console config - app show error (module with id=pages not found, in line 27 m150429_155009_create_page_table.php)

**Comment by bupy7** [comment]
@stronglab Give me your a config file, version Yii2 framework, and structure your the application. 
The **main** config file it **common** config file all application. Therefore, a migration must work.

**Comment by stronglab** [comment]
@bupy7 Im use basic application, there is no common config. 
https://github.com/yiisoft/yii2-app-basic/tree/master/config

**Comment by bupy7** [comment]
@stronglab well then you need add a module `pages` in `console.php` and `web.php`.

**Comment by bupy7** [comment]
@stronglab you have solved the problem?

**Comment by stronglab** [comment]
@bupy7 yes, solved, but i think add module in console.php is wrong. Maybe need load main config in migration and get pages module?

**Comment by bupy7** [comment]
@stronglab why is it wrong? module may be contain console commands for management pages to future) so far so good)

**Comment by stronglab** [comment]
@bupy7 imho this is redundancy of code)

**Comment by bupy7** [comment]
@stronglab yes, i agree
